In [22]:
import numpy as np
import pandas as pd
from scipy import stats
from math import sqrt

In [16]:
df=np.random.normal(size=(2,3))
df1=pd.DataFrame(df)

In [17]:
df1.to_csv('df1.csv')

In [19]:
df

array([[0.60999898, 1.12147517, 0.30912517],
       [0.31396299, 0.68160179, 2.51337631]])

In [32]:

stats.zscore(df[0])


array([-0.20934533,  1.31592446, -1.10657912])

In [33]:

stats.zscore(df[1])

array([-0.88953897, -0.50735463,  1.39689359])

In [30]:
p=0.025
stats.norm.ppf(p)


-1.9599639845400545

In [36]:
#10 ages and you are checking whether avg age is 30 or not.
#H0: The average age is 30
#H1: The average age is not 30.
ages = np.array([32,34,29,29,22,39,38,37,38,36,30,26,22,22])
print(ages)
#mean of the age 
ages_mean = np.mean(ages)
print(ages_mean)
#One Sample t-test
tset, pval = stats.ttest_1samp(ages, 30)
print('p-values',pval)
if pval < 0.05:    # alpha value is 0.05 or 5%
   print(" we are rejecting null hypothesis")
else:
  print("we do not reject null hypothesis")


[32 34 29 29 22 39 38 37 38 36 30 26 22 22]
31.0
p-values 0.5605155888171379
we do not reject null hypothesis
